AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/dummy/db/**/*'
    - 'tmp/**/*'
    - 'lib/generators/vertigo/rtm/install/templates/**/*'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb
